"""Initial migration

Revision ID: a017d62d42c5
Revises: 1610d2af7d59
Create Date: 2020-12-19 15:35:21.738642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a017d62d42c5'
down_revision = '1610d2af7d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=True),
    sa.Column('surname', sa.String(length=35), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=True),
    sa.Column('orders', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('customerid')
    )
    op.create_table('orders',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_table('products',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('productname', sa.String(length=75), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('xsstocklevel', sa.Integer(), nullable=True),
    sa.Column('sstocklevel', sa.Integer(), nullable=True),
    sa.Column('mstocklevel', sa.Integer(), nullable=True),
    sa.Column('lstocklevel', sa.Integer(), nullable=True),
    sa.Column('xlstocklevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('productid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
