"""Initial migration4

Revision ID: a64debb2b7ec
Revises: 77a842d61544
Create Date: 2020-12-20 02:04:27.103155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64debb2b7ec'
down_revision = '77a842d61544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('range', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'range')
    # ### end Alembic commands ###
