"""fifth mig

Revision ID: aa2084351472
Revises: fba39cc33239
Create Date: 2020-12-20 23:48:41.895795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2084351472'
down_revision = 'fba39cc33239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('basket', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'basket')
    # ### end Alembic commands ###
