"""Second mig

Revision ID: b75a93533bd8
Revises: aa2084351472
Create Date: 2020-12-23 20:13:11.105180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75a93533bd8'
down_revision = 'aa2084351472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('basketcontent', sa.PickleType(), nullable=True))
    op.drop_column('customers', 'basket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('basket', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('customers', 'basketcontent')
    # ### end Alembic commands ###
