"""empty message

Revision ID: e491084d7c2d
Revises: b75a93533bd8
Create Date: 2021-01-03 22:26:27.252288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e491084d7c2d'
down_revision = 'b75a93533bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('customerid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['customerid'], ['customers.customerid'], ),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], ),
    sa.PrimaryKeyConstraint('customerid', 'productid')
    )
    op.add_column('customers', sa.Column('orders', sa.String(length=50), nullable=True))
    op.drop_column('customers', 'basketcontent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('basketcontent', sa.BLOB(), nullable=True))
    op.drop_column('customers', 'orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
